model: 'MiniROAD'
data_name: 'FINEACTION'
task: 'OAD'
loss: 'NONUNIFORM'
metric: 'AP'
optimizer: 'AdamW'
device: 'cuda'
feature_pretrained: 'kinetics'
root_path: './data/FINEACTION'
rgb_type: 'rgb_kinetics_i3d'
flow_type: 'flow_kinetics_i3d'
annotation_type: 'target_perframe'
video_list_path: 'data_info/./video_list_fineaction.json'
output_path: './output'
window_size: 128
batch_size: 128 
test_batch_size: 1 
num_epoch: 5
lr: 0.0001
weight_decay: 0.05
num_workers: 4
dropout: 0.20
num_classes: 107 # including background
embedding_dim: 2048
hidden_dim: 1024
num_layers: 1
stride: 3